version: "3.7"
services:
  mailhog:
    image: reusserdesign/mailhog
    restart: always
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./data:/maildir
    user: root
    expose:
      - 1025
      - 8025
    ports:
      - 1025:1025
      - 8025:8025
    healthcheck:
      test: echo | telnet 127.0.0.1 1025
